# Generated by Django 4.0.4 on 2022-04-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_man_sys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
