# Generated by Django 4.0.4 on 2022-04-20 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib_man_sys', '0002_alter_books_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
