# Generated by Django 4.0.4 on 2022-04-20 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib_man_sys', '0003_rename_books_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminUser',
            new_name='User',
        ),
    ]
