# Generated by Django 4.0.4 on 2022-04-21 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib_man_sys', '0004_rename_adminuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
